// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCo25fTFiD3M9-oCVBOPZluCBAwUNa7_b8',
    appId: '1:308917078885:web:cc0d6ec9b4aefe9978ef8c',
    messagingSenderId: '308917078885',
    projectId: 'my-flt-notes-app',
    authDomain: 'my-flt-notes-app.firebaseapp.com',
    storageBucket: 'my-flt-notes-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhOEGbFs2aI6Nqu0vvE4sTzWXh9vpW25k',
    appId: '1:308917078885:android:b40c84c2217a203f78ef8c',
    messagingSenderId: '308917078885',
    projectId: 'my-flt-notes-app',
    storageBucket: 'my-flt-notes-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwTOIG38Rx1v6pndHVt8N4lW_0qyadQnU',
    appId: '1:308917078885:ios:7c3c41da18d7072078ef8c',
    messagingSenderId: '308917078885',
    projectId: 'my-flt-notes-app',
    storageBucket: 'my-flt-notes-app.appspot.com',
    iosClientId: '308917078885-ohh2586tti6brugfsk91lgu92clmgvm2.apps.googleusercontent.com',
    iosBundleId: 'com.aizazhaider.mynotes',
  );
}
